version: "3.8"

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # Ánh xạ cổng ra ngoài
    env_file:
      - .env # Báo cho Docker biết để đọc file .env ở máy bạn
    restart: unless-stopped
